#ifndef CEPHES_LDOUBLE
#define CEPHES_LDOUBLE 1

#ifdef __cplusplus
extern "C" {
#endif

long double acoshl(long double x);
int airyl(long double, long double *, long double *, long double *, long double *);
long double asinl(long double);
long double acosl(long double);
long double asinhl(long double x);
long double atanl(long double);
long double atan2l(long double y, long double x);
long double atanhl(long double);
long double bdtrcl(int k, int n, long double p);
long double bdtrl(int k, int n, long double p);
long double bdtril(int k, int n, long double y);
long double betal(long double a, long double b);
long double lbetal(long double a, long double b);
long double btdtrl(long double a, long double b, long double x);
long double cbrtl(long double);
long double chbevll(long double, void *, int);
long double chdtrcl(long double df, long double x);
long double chdtrl(long double df, long double x);
long double chdtril(long double df, long double y);
void clogl(cmplx *z, cmplx *w);
void cexpl(cmplx *z, cmplx *w);
void csinl(cmplx *z, cmplx *w);
void ccosl(cmplx *z, cmplx *w);
void ctanl(cmplx *z, cmplx *w);
void ccotl(cmplx *z, cmplx *w);
void casinl(cmplx *z, cmplx *w);
void cacosl(cmplx *z, cmplx *w);
void catanl(cmplx *z, cmplx *w);
void caddl(cmplx *a, cmplx *b, cmplx *c);
void csubl(cmplx *a, cmplx *b, cmplx *c);
void cmull(cmplx *a, cmplx *b, cmplx *c);
void cdivl(cmplx *a, cmplx *b, cmplx *c);
void cmovl(void *a, void *b);
void cnegl(cmplx *a);
long double cabsl(cmplx *z);
void csqrtl(cmplx *z, cmplx *w);
long double hypotl(long double, long double);
long double coshl(long double);
long double dawsnl(long double xx);
void eigensl(long double A[], long double RR[], long double E[], int N);
long double elliel(long double, long double);
long double ellikl(long double, long double);
long double ellpel(long double);
int ellpjl(long double u, long double m, long double *sn, long double *cn, long double *dn, long double *ph);
long double ellpkl(long double);
long double exp10l(long double);
long double exp1ml(long double);
long double exp2l(long double);
long double expnl(int n, long double x);
long double facl(int i);
long double fdtrcl(int ia, int ib, long double x);
long double fdtrl(int ia, int ib, long double x);
long double fdtril(int ia, int ib, long double y);
int fftrl(long double x[], int m0, long double sine[]);
long double ceill(long double x);
long double fabsl(long double);
long double floorl(long double);
long double frexpl(long double, int *);
long double ldexpl(long double, int);
int signbitl(long double);
int isnanl(long double);
int isfinitel(long double);
long double polevll(long double, void *, int);
long double p1evll(long double, void *, int);
long double expl(long double);
long double logl(long double);
long double sinl(long double);
long double cosl(long double);
long double sqrtl(long double);
int fresnll(long double xxa, long double *ssa, long double *cca);
long double gammal(long double);
long double lgaml(long double);
long double gdtrl(long double a, long double b, long double x);
long double gdtrcl(long double a, long double b, long double x);
int gelsl(long double A[], long double R[], int M, long double EPS, long double AUX[]);
long double hyp2f1l(long double a, long double b, long double c, long double x);
long double hypergl(long double, long double, long double);
long double hyp2f0l(long double a, long double b, long double x, int type, long double *err);
long double i0l(long double);
long double i0el(long double x);
long double i1l(long double);
long double i1el(long double x);
long double igamcl(long double, long double);
long double igaml(long double, long double);
long double igamil(long double, long double);
long double incbetl(long double, long double, long double);
long double incbil(long double, long double, long double);
long double ivl(long double v, long double x);
long double j0l(long double);
long double y0l(long double);
long double j1l(long double);
long double y1l(long double);
long double jnl(int n, long double x);
long double jvl(long double, long double);
long double k0l(long double x);
long double k0el(long double x);
long double k1l(long double x);
long double k1el(long double x);
long double knl(int nn, long double x);
int levnsnl(int n, long double r[], long double a[], long double e[], long double refl[]);
long double log10l(long double);
long double log2l(long double);
long lrandl(void);
long lsqrtl(long x);
int minvl(long double A[], long double X[], int n, long double B[], int IPS[]);
int mmmpyl(int r, int c, long double *A, long double *B, long double *Y);
int mtherrl(char *name, int code);
int mtranspl(int n, long double *A, long double *T);
int mvmpyl(int r, int c, long double *A, long double *V, long double *Y);
long double nbdtrcl(int k, int n, long double p);
long double nbdtrl(int k, int n, long double p);
long double nbdtril(int k, int n, long double p);
long double ndtrl(long double a);
long double erfcl(long double);
long double erfl(long double);
long double ndtril(long double);
long double pdtrcl(int k, long double m);
long double pdtrl(int k, long double m);
long double pdtril(int k, long double y);
long double powl(long double, long double);
long double powil(long double, int);
long double psil(long double);
void reversl(long double y[], long double x[], int n);
long double rgammal(long double x);
long double roundl(long double);
int sprecl(void);
int dprecl(void);
int ldprecl(void);
int shichil(long double x, long double *si, long double *ci);
int sicil(long double x, long double *si, long double *ci);
long double simpsnl(long double f[], long double delta);
int simql(long double A[], long double B[], long double X[], int n, int flag, int IPS[]);
long double radianl(long double d, long double m, long double s);
/* Rename to avoid ugly surprises.
int sincosl(long double x, long double *s, long double *c, int flg);
*/
int sincosdgl(long double x, long double *s, long double *c, int flg);
long double sindgl(long double x);
long double cosdgl(long double x);
long double sinhl(long double);
long double spencel(long double);
long double stdtrl(int k, long double t);
long double stdtril(int k, long double p);
long double onef2l(long double a, long double b, long double c, long double x, long double *err);
long double threef0l(long double a, long double b, long double c, long double x, long double *err);
long double struvel(long double v, long double x);
long double tanl(long double);
long double cotl(long double);
long double tandgl(long double x);
long double cotdgl(long double x);
long double tanhl(long double);
long double log1pl(long double);
long double exmp1l(long double);
long double cosm1l(long double x);
long double ynl(int, long double);
long double zetal(long double x, long double q);
long double zetacl(long double);
int drandl(long double *a);
long double smirnovl(int, long double);
long double smirnovil(int, long double);
long double kolmogorovl(long double);
long double kolmogil(long double);

#ifdef __cplusplus
}
#endif

#endif // CEPHES_LDOUBLE
