# src/cmake/SasfitSourceFiles.cmake
#
# Copyright (c) 2008-2022, Paul Scherrer Institute (PSI)
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the <organization> nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Author(s) of this file:
#   Ingo Bressler (ingo.bressler@bam.de)
#   Joachim Kohlbrecher (joachim.kohlbrecher@psi.ch)
#
#############################################################################
# A Cmake module to provide utility functions often used
# in sasfit cmake scripts
#
# This module expects to live in <sasfit-dir>/src/cmake

# cmake_minimum_required(VERSION 3.0)
cmake_policy(SET CMP0011 NEW)

set(SOURCE_sasfit_common
	sasfit_timer.c
	sasfit_gamma.c
	sasfit_utils.c
	sasfit_trapzd.c
	sasfit_integrate.c
	sasfit_intde2.c
	sasfit_mem.c
	sasfit_message.c
	sasfit_function.c
	sasfit_error_common.c
	sasfit_eps.c
	sasfit_plugin_func.c
	sasfit_plugin_api.c
	sasfit_common.c
	sasfit_qwe.c
	f2c_utils/sasfit_dmilay.c
	f2c_utils/sasfit_struve_h0h1.c
	f2c_utils/sasfit_robertus_utils.c
	f2c_utils/sasfit_zspow.c
	f2c_utils/sasfit_mie_utils.c
	f2c_utils/sasfit_th36.c
	f2c_utils/sasfit_miev0.c
	f2c_utils/sasfit_pfq.c
	cubature/hcubature.c
	cubature/pcubature.c
	Ogata/FBT.cpp
	Ogata/sasfit_FBT.cpp
	Ogata/FBT.h
	libcerf_1.5/erfcx.c
	libcerf_1.5/err_fcts.c
	libcerf_1.5/im_w_of_x.c
	libcerf_1.5/w_of_z.c
	sasfit_compare_dist/sasfit_compare.c
	sasfit_compare_dist/sasfit_correlation.c
	sasfit_compare_dist/ot1d/include/OT1D.hpp
	sasfit_compare_dist/ot1d/include/parasort.h
	sasfit_compare_dist/ot1d/include/pdqsort.h
	multidiminte/src/multi_dim_inte.c
	multidiminte/src/handle.c
	multidiminte/src/tanhsinh/tanhsinh.c
	multidiminte/src/tanhsinh/tanhsinh.h
	multidiminte/src/Lebedev/sphere_lebedev_rule.c
	multidiminte/src/Lebedev/sphere_lebedev_rule.h	
	multidiminte/src/spherical_t_design/Design_1002000_1000_random.h
	multidiminte/src/spherical_t_design/Design_1002000_1000_random_phi_theta.h
	multidiminte/src/spherical_t_design/Design_1002000_1000_random_xyz.h
	multidiminte/src/spherical_t_design/Design_130000_500_random.h
	multidiminte/src/spherical_t_design/Design_130000_500_random_phi_theta.h
	multidiminte/src/spherical_t_design/Design_130000_500_random_xyz.h
	multidiminte/src/spherical_t_design/Design_21000_200_random.h
	multidiminte/src/spherical_t_design/Design_21000_200_random_phi_theta.h
	multidiminte/src/spherical_t_design/Design_21000_200_random_xyz.h
	multidiminte/src/spherical_t_design/Design_21000_200_spiral.h
	multidiminte/src/spherical_t_design/Design_21000_200_spiral_phi_theta.h
	multidiminte/src/spherical_t_design/Design_21000_200_spiral_xyz.h
	multidiminte/src/spherical_t_design/Design_520000_1000_random.h
	multidiminte/src/spherical_t_design/Design_520000_1000_random_phi_theta.h
	multidiminte/src/spherical_t_design/Design_520000_1000_random_xyz.h
	multidiminte/src/spherical_t_design/Design_5200_100_random.h
	multidiminte/src/spherical_t_design/Design_5200_100_random_phi_theta.h
	multidiminte/src/spherical_t_design/Design_5200_100_random_xyz.h
	multidiminte/src/spherical_t_design/Design_5200_100_spiral.h
	multidiminte/src/spherical_t_design/Design_5200_100_spiral_phi_theta.h
	multidiminte/src/spherical_t_design/Design_5200_100_spiral_xyz.h
	multidiminte/src/spherical_t_design/Design_xxx_xxxx.h
	multidiminte/src/spherical_t_design/N001_M2_Inv.h
	multidiminte/src/spherical_t_design/N002_M4_Tetra.h
	multidiminte/src/spherical_t_design/N003_M6_Octa.h
	multidiminte/src/spherical_t_design/N005_M12_Ico.h
	multidiminte/src/spherical_t_design/N007_M24_Octa.h
	multidiminte/src/spherical_t_design/N008_M36_Tetra.h
	multidiminte/src/spherical_t_design/N009_M48_Octa.h
	multidiminte/src/spherical_t_design/N010_M60_Tetra.h
	multidiminte/src/spherical_t_design/N011_M70_C5.h
	multidiminte/src/spherical_t_design/N012_M84_Tetra.h
	multidiminte/src/spherical_t_design/N013_M94_Inv.h
	multidiminte/src/spherical_t_design/N014_M108_Tetra.h
	multidiminte/src/spherical_t_design/N015_M120_Octa.h
	multidiminte/src/spherical_t_design/N016_M144_Tetra.h
	multidiminte/src/spherical_t_design/N017_M156_Tetra.h
	multidiminte/src/spherical_t_design/N018_M180_Tetra.h
	multidiminte/src/spherical_t_design/N019_M192_C3.h
	multidiminte/src/spherical_t_design/N020_M216_Tetra.h
	multidiminte/src/spherical_t_design/N021_M234_C3.h
	multidiminte/src/spherical_t_design/N022_M264_Octa.h
	multidiminte/src/spherical_t_design/N023_M278_C3.h
	multidiminte/src/spherical_t_design/N024_M312_Octa.h
	multidiminte/src/spherical_t_design/N025_M328_Inv.h
	multidiminte/src/spherical_t_design/N026_M360_Octa.h
	multidiminte/src/spherical_t_design/N027_M380_C3.h
	multidiminte/src/spherical_t_design/N028_M420_Tetra.h
	multidiminte/src/spherical_t_design/N029_M432_Ico.h
	multidiminte/src/spherical_t_design/N030_M480_Octa.h
	multidiminte/src/spherical_t_design/N031_M498_C3.h
	multidiminte/src/spherical_t_design/N032_M540_Tetra.h
	multidiminte/src/spherical_t_design/N033_M564_C3.h
	multidiminte/src/spherical_t_design/N034_M612_Ico.h
	multidiminte/src/spherical_t_design/N035_M632_C3.h
	multidiminte/src/spherical_t_design/N036_M684_Tetra.h
	multidiminte/src/spherical_t_design/N037_M706_Inv.h
	multidiminte/src/spherical_t_design/N038_M756_Tetra.h
	multidiminte/src/spherical_t_design/N039_M782_C3.h
	multidiminte/src/spherical_t_design/N040_M840_Octa.h
	multidiminte/src/spherical_t_design/N041_M864_C3.h
	multidiminte/src/spherical_t_design/N042_M924_Tetra.h
	multidiminte/src/spherical_t_design/N044_M1008_Octa.h
	multidiminte/src/spherical_t_design/N046_M1104_Octa.h
	multidiminte/src/spherical_t_design/N048_M1200_Octa.h
	multidiminte/src/spherical_t_design/N050_M1296_Octa.h
	multidiminte/src/spherical_t_design/N052_M1404_Tetra.h
	multidiminte/src/spherical_t_design/N054_M1512_Ico.h
	multidiminte/src/spherical_t_design/N056_M1620_Tetra.h
	multidiminte/src/spherical_t_design/N058_M1740_Tetra.h
	multidiminte/src/spherical_t_design/N060_M1860_Tetra.h
	multidiminte/src/spherical_t_design/N062_M1980_Tetra.h
	multidiminte/src/spherical_t_design/N064_M2112_Ico.h
	multidiminte/src/spherical_t_design/N066_M2244_Tetra.h
	multidiminte/src/spherical_t_design/N068_M2376_Octa.h
	multidiminte/src/spherical_t_design/N070_M2520_Octa.h
	multidiminte/src/spherical_t_design/N072_M2664_Octa.h
	multidiminte/src/spherical_t_design/N074_M2808_Octa.h
	multidiminte/src/spherical_t_design/N076_M2964_Tetra.h
	multidiminte/src/spherical_t_design/N078_M3120_Octa.h
	multidiminte/src/spherical_t_design/N080_M3276_Tetra.h
	multidiminte/src/spherical_t_design/N082_M3444_Tetra.h
	multidiminte/src/spherical_t_design/N084_M3612_Ico.h
	multidiminte/src/spherical_t_design/N086_M3780_Tetra.h
	multidiminte/src/spherical_t_design/N088_M3960_Octa.h
	multidiminte/src/spherical_t_design/N090_M4140_Tetra.h
	multidiminte/src/spherical_t_design/N094_M4512_Ico.h
	multidiminte/src/spherical_t_design/N098_M4896_Octa.h
	multidiminte/src/spherical_t_design/N100_M5100_Tetra.h
	multidiminte/src/spherical_t_design/N114_M6612_Ico.h
	multidiminte/src/spherical_t_design/N124_M7812_Ico.h
	multidiminte/src/spherical_t_design/spherical_t_rule.c
	multidiminte/src/spherical_t_design/spherical_t_rule.h
	multidiminte/src/AllFrolovPoints/pointsets/Frolov.c
	include/Frolov.h
	quasimontecarlo/quasimontecarlo.h
	quasimontecarlo/quasimontecarlo.c
	quasimontecarlo/Burley2020Scrambling/faure05.cpp
	quasimontecarlo/Burley2020Scrambling/faure05.h
	quasimontecarlo/Burley2020Scrambling/genpoints.cpp
	quasimontecarlo/Burley2020Scrambling/genpoints.h
	quasimontecarlo/Burley2020Scrambling/owenhash.h
	quasimontecarlo/Burley2020Scrambling/pcg.h
	quasimontecarlo/Burley2020Scrambling/radicalinverse.h
	quasimontecarlo/Burley2020Scrambling/sobol.cpp
	quasimontecarlo/Burley2020Scrambling/sobol.h
)

set(SOURCE_sasfit_core
	sasfit_sd.c
	sasfit_sq.c
	sasfit_ff.c
	sasfit_analytpar.c
	sasfit_analytpar_utils.c
	sasfit_vector.c
	sasfit_env.c
	sasfit_error_core.c
	sasfit_core.c
	sasfit_plugin_backend.c
	sasfit_plugin_db.c
	sasfit_tclcmd.c
	sasfit_2d.c
)

set(SOURCE_sasfit_sd
	sasfit_sd_beta.c
	sasfit_sd_Delta.c
	sasfit_sd_fractalSD.c
	sasfit_sd_gammaSD.c
	sasfit_sd_GaussDistribution.c
	sasfit_sd_GEV.c
	sasfit_sd_GEX.c
	sasfit_sd_LogNorm.c
	sasfit_sd_Maxwell.c
	sasfit_sd_Monodisperse.c
	sasfit_sd_SchulzZimm.c
	sasfit_sd_Triangular.c
	sasfit_sd_Uniform.c
	sasfit_sd_Weibull.c
	sasfit_sd_LogNorm_fp.c
	sasfit_sd_Rn_Triangular.c
	sasfit_sd_BiLogNorm.c
)

set(SOURCE_sasfit_sq
	sasfit_sq_BabaAhmed2.c
	sasfit_sq_BabaAhmed.c
	sasfit_sq_CorrelationHole.c
	sasfit_sq_CriticalScattering1.c
	sasfit_sq_Cylinder_PRISM.c
	sasfit_sq_HardSphere.c
	sasfit_sq_HayterPenfoldMSA.c
	sasfit_sq_LocalOrderModel.c
	sasfit_sq_MacroIon.c
	sasfit_sq_None.c
	sasfit_sq_RandomDistributionModel.c
	sasfit_sq_SquareWell2.c
	sasfit_sq_SquareWell.c
	sasfit_sq_StickyHardSphere2.c
	sasfit_sq_StickyHardSphere.c
	sasfit_sq_ThinDiscs.c
	sasfit_sq_ThinCylindricalShell.c
	sasfit_sq_ThinSphericalShell.c
	sasfit_sq_ThinSquareWell.c
)

set(SOURCE_sasfit_ff
	psi_a_b/sasfit_ff_a.c
	psi_a_b/sasfit_ff_b.c
	sasfit_ff_Andrea1.c
	sasfit_ff_background.c
	sasfit_ff_BiLayeredVesicle.c
	sasfit_ff_BiLayerGauss.c
	sasfit_ff_BroadPeak.c
	sasfit_ff_cyl_mic.c
	cyl_rwbrush/utils.c
	cyl_rwbrush/sasfit_ff_cyl_rwbrush.c
	cyl_rwbrush/sasfit_ff_cyl_rwbrush_nagg.c
	cyl_rwbrush/sasfit_ff_cyl_rwbrush_rc.c
	disc_rwbrush/sasfit_ff_disc_rwbrush.c
	disc_rwbrush/sasfit_ff_disc_rwbrush_lc.c
	disc_rwbrush/sasfit_ff_disc_rwbrush_nagg.c
	sasfit_ff_DLS_Sphere_RDG.c
	sasfit_ff_DoubleShell_withSD.c
	ellip_rwbrush/utils.c
	ellip_rwbrush/sasfit_ff_ellip_rwbrush.c
	ellip_rwbrush/sasfit_ff_ellip_rwbrush_rc.c
	ellip_rwbrush/sasfit_ff_ellip_rwbrush_nagg.c
	ellip_core_shell/sasfit_ff_ellip_core_shell.c
	ellip/utils.c
	ellip/sasfit_ff_ellip_1.c
	ellip/sasfit_ff_ellip_2.c
	sasfit_ff_ExpShell.c
	sasfit_ff_Fractal.c
	sasfit_ff_francois.c
	sasfit_ff_guinier.c
	sasfit_ff_HardSphere.c
	sasfit_ff_homogenousXS.c
	sasfit_ff_hysteresesFFpsiStrobo.c
	magnetic_shell/sasfit_ff_magnetic_shell_aniso.c
	magnetic_shell/sasfit_ff_magnetic_shell_psi.c
	magnetic_shell/sasfit_ff_magnetic_shell_cross.c
	p_cs/sasfit_ff_Pcs_ellCylSh.c
	p_cs/sasfit_ff_Pcs_homogeneousCyl.c
	p_cs/sasfit_ff_Pcs_homogeneousPlanar.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi_strobo_sq.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi_strobo_sq_l2x_pol_albr.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi_strobo2.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi_strobo_sq_l2x.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi_tisane.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi_strobo_sq_lx.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi_strobo_bt1.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi_strobo.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi_strobo_sq_l2modx_pol.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi_strobo_sq_l2x_pol_albr_stat.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi_strobo_ppsi.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi_cross.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi_aniso.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi_strobo_sq_l2x_pol.c
	superparamagnetic_ff_psi/sasfit_ff_superparamagnetic_ff_psi_iso.c
	sasfit_ff_JuelichDoubleShell.c
	sasfit_ff_sphere.c
	sasfit_ff_KholodenkoWorm.c
	sasfit_ff_Ksh.c
	sasfit_ff_KShellcompr.c
	sasfit_ff_KshExp.c
	sasfit_ff_Kshlin.c
	sasfit_ff_Langevin.c
	sasfit_ff_LayeredCentroSymmetricXS.c
	sasfit_ff_LinShell.c
	sasfit_ff_MLVesicleFrielinghaus.c
	sasfit_ff_MultiLamellarVesicle.c
	sasfit_ff_OrnsteinZernike.c
	sasfit_ff_RNDMultiLamellarVesicle2.c
	sasfit_ff_RNDMultiLamellarVesicle.c
	sasfit_ff_Robertus1.c
	sasfit_ff_Robertus2.c
	sasfit_ff_Robertus3.c
	sasfit_ff_Rod_Exp_Profile.c
	sasfit_ff_Rod_Gauss_Profile.c
	sasfit_ff_Rodlike_BlockCopolymerMicelle.c
	sasfit_ff_Rod_R_ma_Profile.c
	sasfit_ff_Rod_RWbrush.c
	sasfit_ff_shearedCylinder.c
	sasfit_ff_Shellcompr.c
	sasfit_ff_spherical_shell.c
	sasfit_ff_Spinodal.c
	sasfit_ff_StackDiscs.c
	sasfit_ff_StickyHardSphere.c
	sasfit_ff_TeubnerStrey.c
	sasfit_ff_ThinCylShell_homogenousXS.c
	sasfit_ff_ThinDisc_homogenousXS.c
	sasfit_ff_ThinEllShell_homogenousXS.c
	sasfit_ff_ThinSphShell_homogenousXS.c
	sasfit_ff_triaxEllShell1.c
	sasfit_ff_TripleLayeredHomogeneousCentroSymmetricXS.c
	sasfit_ff_two_attached_spheres.c
	sasfit_ff_TwoInfinitelyThinPlates.c
	sasfit_ff_UnifiedExponetialPowerLaw2.c
	sasfit_ff_UnifiedExponetialPowerLaw.c
	sasfit_ff_VeryLongCylindricalShell.c
	sasfit_ff_very_long_cyl_w_gauss_chains.c
	sasfit_ff_WormLikeChainEXV.c
	sasfit_ff_Worm_R_ma_Profile.c
	sasfit_ff_Worm_RWbrush.c
	sasfit_ff_worm_w_gauss_chains.c
	sasfit_planar_gausschains.c
)

set(SOURCE_sasfit_oz
	sasfit_oz_solver.c
	sasfit_oz_potential_hard_sphere.c
	sasfit_oz_potential_sticky_hard_sphere.c
	sasfit_oz_potential_soft_sphere.c
	sasfit_oz_potential_lennard_jones.c
	sasfit_oz_potential_ionic_microgel.c
	sasfit_oz_potential_depletion.c
	sasfit_oz_potential_psm.c
	sasfit_oz_potential_ggcm-n.c
	sasfit_oz_potential_dlvo.c
	sasfit_oz_potential_dlvo_hydra.c
	sasfit_oz_potential_star_Likos.c
	sasfit_oz_potential_HS_3Yukawa.c
	sasfit_oz_potential_FermiDistributionModel.c
	sasfit_oz_potential_square_well.c
	sasfit_oz_potential_piecewise_constant_HS.c
	sasfit_oz_tclcmd.c
)

set(SOURCE_sasfit_fixed_point_acc
	sasfit_fixed_point_acc.c
)

set(SOURCE_sasfit_frida
	sasfit_frida_solver.c
	nnls.c
)

set(SOURCE_sasfit_jburkardt
	blas0.c
	blas1_d.c
	linpack_d.c
	sparse_grid_cc.c
	sparse_grid_hw.c
	smolyak.c
	filon_rule.c
	jburkardt_utils.c
	cdflib.c
)

set(SOURCE_sasfit_old
# former sasfit main
	bessi0.c
	bessj0.c
	bessj1.c
	SASFIT_trapzd.c
	SASFIT_polint.c
	SASFIT_qromb.c
	SASFIT_x_tcl.c
	sasfit.c
	SASFIT_resolution.c
# former sasfit extrapol
	ei.c
	erf.c
	gammp.c
	jfrac.c
	pol.c
	SASFIT_covsrt.c
	sasfit_extrapol.c
	SASFIT_fit.c
	SASFIT_gammaq.c
	SASFIT_gaussj.c
	SASFIT_gcf.c
	SASFIT_gser.c
	SASFIT_indexx.c
	SASFIT_mrqcof.c
	SASFIT_mrqmin.c
	SASFIT_nrutil.c
# former sasfit DLS
	DLS/DLS_g2_1.c
	DLS/DLS_models.c
)

set(SOURCE_f2c
	abort_.c
	#    arithchk.c
	backspac.c
	c_abs.c
	cabs.c
	c_cos.c
	c_div.c
	c_exp.c
	c_log.c
	close.c
	c_sin.c
	c_sqrt.c
	d_abs.c
	d_acos.c
	d_asin.c
	d_atan.c
	d_atn2.c
	d_cnjg.c
	d_cos.c
	d_cosh.c
	d_dim.c
	#    derf_.c
	#    derfc_.c
	d_exp.c
	dfe.c
	d_imag.c
	d_int.c
	d_lg10.c
	d_log.c
	d_mod.c
	d_nint.c
	dolio.c
	d_prod.c
	d_sign.c
	d_sin.c
	d_sinh.c
	d_sqrt.c
	d_tan.c
	d_tanh.c
	dtime_.c
	due.c
	ef1asc_.c
	ef1cmc_.c
	endfile.c
	#    erf_.c
	#    erfc_.c
	err.c
	etime_.c
	exit_.c
	f77_aloc.c
	f77vers.c
	fmt.c
	fmtlib.c
	ftell64_.c
	ftell_.c
	#    getarg_.c
	getenv_.c
	h_abs.c
	h_dim.c
	h_dnnt.c
	h_indx.c
	h_len.c
	hl_ge.c
	hl_gt.c
	hl_le.c
	hl_lt.c
	h_mod.c
	h_nint.c
	h_sign.c
	i77vers.c
	i_abs.c
	#    iargc_.c
	i_dim.c
	i_dnnt.c
	i_indx.c
	iio.c
	i_len.c
	ilnw.c
	i_mod.c
	i_nint.c
	inquire.c
	i_sign.c
	lbitbits.c
	lbitshft.c
	l_ge.c
	l_gt.c
	l_le.c
	l_lt.c
	lread.c
	lwrite.c
	#    main.c
	open.c
	pow_ci.c
	pow_dd.c
	pow_di.c
	pow_hh.c
	pow_ii.c
	pow_qq.c
	pow_ri.c
	pow_zi.c
	pow_zz.c
	qbitbits.c
	qbitshft.c
	r_abs.c
	r_acos.c
	r_asin.c
	r_atan.c
	r_atn2.c
	r_cnjg.c
	r_cos.c
	r_cosh.c
	rdfmt.c
	r_dim.c
	rewind.c
	r_exp.c
	r_imag.c
	r_int.c
	r_lg10.c
	r_log.c
	r_mod.c
	r_nint.c
	rsfe.c
	r_sign.c
	r_sin.c
	r_sinh.c
	rsli.c
	rsne.c
	r_sqrt.c
	r_tan.c
	r_tanh.c
	s_cat.c
	s_cmp.c
	s_copy.c
	sfe.c
	sig_die.c
	signal_.c
	signbit.c
	s_paus.c
	s_rnge.c
	s_stop.c
	sue.c
	system_.c
	typesize.c
	uio.c
	uninit.c
	util.c
	wref.c
	wrtfmt.c
	wsfe.c
	wsle.c
	wsne.c
	xwsne.c
	z_abs.c
	z_cos.c
	z_div.c
	z_exp.c
	z_log.c
	z_sin.c
	z_sqrt.c
	sasfit_wofz.c
)

