# -*- coding: utf-8 -*-
"""Sphinx configuration for the pyozgui / ozLib documentation.

Build with:

    cd src/pyOZgui/docs
    python -m sphinx -b html . _build

and open _build/index.html. Needs: sphinx, myst-parser, sphinx-rtd-theme.

WHY SPHINX AT ALL, given a perfectly readable Markdown manual exists.

Because the manual's reference tables -- 21 potentials with their argument
tuples, 24 closures, 5 solvers -- were generated by introspection and are now
FROZEN as text. The moment a potential is added they become wrong, and wrong
in the way that is hardest to notice: quietly, with nobody looking. autodoc
reads the source at build time, so the API half of the documentation cannot
drift from the code.

The narrative half is a different matter and is deliberately left in
Markdown. The sign conventions, the r_max trap, the branch-selection warning
-- none of that is derivable from a signature, and it is the part a user
actually needs. Converting it to reStructuredText would buy nothing and would
make it less likely to be kept current.
"""
import os
import sys

#The package is not installed; point autodoc at the source tree. From docs/
#that is ../src/pyozgui/, which is where ozLib.py lives.
sys.path.insert(0, os.path.abspath(os.path.join("..", "src", "pyozgui")))

project = "pyozgui / ozLib"
copyright = "2026, Paul Scherrer Institute"
author = "Joachim Kohlbrecher"
release = "0.1"

extensions = [
    "sphinx.ext.autodoc",       # API reference generated FROM the docstrings
    "sphinx.ext.napoleon",      # so NumPy/Google-style sections render
    "sphinx.ext.viewcode",      # a [source] link beside every entry
    "sphinx.ext.intersphinx",   # numpy/scipy names become links
    "sphinx.ext.mathjax",
    "myst_parser",              # narrative pages stay Markdown
]

source_suffix = {".rst": "restructuredtext", ".md": "markdown"}
myst_enable_extensions = ["deflist", "colon_fence"]

#EXCLUDE THE WORKING NOTES. docs/ holds a dozen Markdown files that are
#internal -- handover notes, build instructions, test results, the manuscript
#directory. Sphinx picks up every .md it finds and then warns that each is
#"not included in any toctree", which buries the warnings that matter under
#eleven that do not.
#
#ozLib_manual.md is excluded because it is COPIED to manual.md for the build;
#leaving both in would document the same page twice.
exclude_patterns = [
    "_build",
    "ozLib_manual.md",             # copied to manual.md
    "NEXT_SESSION.md",
    "JK_NEXT_SESSION.md",
    "AI_USAGE.md",
    "BUILD_ROBERTUS_RY.md",
    "OZ_solver_naming_conventions.md",
    "README_polydisperse_yukawa.md",
    "polydisperse_yukawa_spec.md",
    "multicomponentUnitTest_results.md",
    "manuscript",                  # the paper, built with LaTeX not Sphinx
]

autodoc_member_order = "bysource"
autodoc_typehints = "description"
autodoc_default_options = {
    "members": True,
    #undoc-members OFF: an entry with no docstring is a name, not
    #documentation, and listing it only pads the page.
    "undoc-members": False,
    "show-inheritance": True,
}

#MOCK THE OPTIONAL BACK ENDS. autodoc imports each module to read its
#docstrings, so anything importable only when an optional dependency is
#present would break the build wherever the docs are made -- and the docs
#will be built in places SUNDIALS is not.
autodoc_mock_imports = [
    "sundials4py", "bumps", "nlopt", "mixscatter", "jscatter",
    "matplotlib", "tkinter",
]

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable", None),
    "scipy": ("https://docs.scipy.org/doc/scipy", None),
}

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
