name: update_webpage

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
    - '.github/**'
    - '*.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_webpage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout webpage repo
        uses: actions/checkout@v2
        with:
          repository: SASfit/sasfit.github.io
          path: webpage
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List current directory structure
        run: |
          echo "Current path: '$(pwd)':"
          ls -la
          echo 'main:'
          ls -la main
          echo 'webpage:'
          ls -la webpage

      - name: Copy over readme content
        run: |
          cp "webpage/index.head" "webpage/index.md"
          # filter initial badges icons and links from section titles
          sed -n '/^#/,$p' "main/Readme.md" | sed -E 's/(^#+[[:space:]]*)\[([[:alnum:][:space:]]+)\].*$/\1\2/' >> "webpage/index.md"

      - name: Generate TOC to show on left side
        run: |
          cd webpage
          pip install md-toc
          mkdir -p _includes
          python3 -m md_toc github index.md | tail -n+2 | sed 's/\(\s*- \)/\1{:.toc}/' > _includes/toc.md

      - name: Commit updated index to webpage repo
        run: |
          cd webpage
          git add _includes; git add -u
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -m "Updated index and TOC from SASfit source" . || true

      - name: Push updates to webpage repo
        run: |
          cd webpage
          git push
